FROM node:22-alpine  
#  เพื่อที่จะบอกว่าใช้ node อะไร

WORKDIR /app

COPY package.json* ./

RUN npm install
RUN npm install -g nodemon

COPY . . 
#  1 จุดจะคือโฟลเดอร์ปัจจุบัน อันที่2คือ App

# จะรันที่พอร์ต 0000
EXPOSE 5000

# docker แบ่งเป็น Array
CMD [ "npm","run","dev" ]